import {
  AlignmentType,
  Document,
  HeadingLevel,
  ImageRun,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from "docx";
import { saveAs } from "file-saver";
import type { Chunk, Dataset, ResultTable } from "../types";
import type { Theme } from "../theme";
import { DEFAULT_THEME } from "../theme";
import { getTest } from "../stats/tests";
import { renderPlotSvg, PLOT_HEIGHT, PLOT_WIDTH } from "../charts/svg";

/** Rasterise an SVG string to PNG bytes via an offscreen canvas (2× for clarity). */
function svgToPng(svg: string, scale = 2): Promise<Uint8Array> {
  return new Promise((resolve, reject) => {
    const blob = new Blob([svg], { type: "image/svg+xml;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = PLOT_WIDTH * scale;
      canvas.height = PLOT_HEIGHT * scale;
      const ctx = canvas.getContext("2d")!;
      ctx.fillStyle = "#ffffff";
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
      URL.revokeObjectURL(url);
      canvas.toBlob((b) => {
        if (!b) return reject(new Error("Canvas export failed"));
        b.arrayBuffer().then((ab) => resolve(new Uint8Array(ab)));
      }, "image/png");
    };
    img.onerror = () => {
      URL.revokeObjectURL(url);
      reject(new Error("SVG rasterisation failed"));
    };
    img.src = url;
  });
}

const hex = (c: string) => c.replace(/^#/, "");

function buildTable(t: ResultTable, theme: Theme): Table {
  const header = new TableRow({
    tableHeader: true,
    children: t.columns.map(
      (c) =>
        new TableCell({
          shading: { fill: hex(theme.ui.thBg) },
          children: [
            new Paragraph({
              children: [new TextRun({ text: String(c), bold: true, color: hex(theme.ui.thText) })],
            }),
          ],
        })
    ),
  });
  const body = t.rows.map(
    (row) =>
      new TableRow({
        children: row.map(
          (cell) =>
            new TableCell({
              children: [new Paragraph({ children: [new TextRun({ text: String(cell) })] })],
            })
        ),
      })
  );
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [header, ...body],
  });
}

export async function exportToWord(
  dataset: Dataset,
  chunks: Chunk[],
  theme: Theme = DEFAULT_THEME
): Promise<void> {
  const children: (Paragraph | Table)[] = [];

  const usedTests = [
    ...new Map(
      chunks.filter((c) => c.result).map((c) => [c.testId, getTest(c.testId)])
    ).values(),
  ];

  // --- Title block ---
  children.push(
    new Paragraph({ text: "Statistical Analysis Report", heading: HeadingLevel.TITLE }),
    new Paragraph({
      children: [
        new TextRun({ text: "Dataset: ", bold: true }),
        new TextRun({ text: dataset.name }),
      ],
    }),
    new Paragraph({
      children: [new TextRun({ text: dataset.description, italics: true, color: "475569" })],
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated by SPSS Killer · ${new Date().toLocaleString()}`,
          color: "94a3b8",
          size: 18,
        }),
      ],
    }),
    new Paragraph({ text: "" })
  );

  // --- Methods (before results) ---
  if (usedTests.length > 0) {
    const methodsSentences = usedTests
      .map((t) => t.methods)
      .filter(Boolean)
      .join(" ");

    children.push(
      new Paragraph({ text: "Methods", heading: HeadingLevel.HEADING_1 }),
      new Paragraph({
        children: [
          new TextRun({
            text:
              "All statistical analyses were performed using SPSS Killer (SPSS Killer, 2026). " +
              methodsSentences +
              " Statistical significance was set at α = 0.05 for all tests.",
          }),
        ],
        spacing: { after: 160 },
      }),
      new Paragraph({ text: "" })
    );
  }

  // --- Results ---
  let n = 0;
  for (const chunk of chunks) {
    if (!chunk.result) continue;
    n++;
    const test = getTest(chunk.testId);
    children.push(
      new Paragraph({ text: `${n}. ${test.name}`, heading: HeadingLevel.HEADING_1 }),
      new Paragraph({
        children: [new TextRun({ text: chunk.result.description })],
        spacing: { after: 120 },
      })
    );

    for (const table of chunk.result.tables) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: table.title, bold: true })],
          spacing: { before: 120, after: 60 },
        }),
        buildTable(table, theme),
        new Paragraph({ text: "" })
      );
    }

    if (chunk.result.plot) {
      try {
        const png = await svgToPng(renderPlotSvg(chunk.result.plot, theme.plot));
        children.push(
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new ImageRun({
                type: "png",
                data: png,
                transformation: { width: 520, height: 325 },
              }),
            ],
          }),
          new Paragraph({ text: "" })
        );
      } catch {
        children.push(new Paragraph({ children: [new TextRun({ text: "[plot could not be rendered]", italics: true })] }));
      }
    }
  }

  if (n === 0) {
    children.push(
      new Paragraph({
        children: [new TextRun({ text: "No completed analyses to export yet.", italics: true })],
      })
    );
  }

  // --- References (end of document) ---
  if (usedTests.length > 0) {
    children.push(
      new Paragraph({ text: "References", heading: HeadingLevel.HEADING_1 }),
      new Paragraph({
        children: [
          new TextRun({
            text: "SPSS Killer. (2026). SPSS Killer: Browser-first statistical analysis [Computer software].",
          }),
        ],
        indent: { left: 360, hanging: 360 },
      })
    );
  }

  const doc = new Document({ sections: [{ children }] });
  const blob = await Packer.toBlob(doc);
  saveAs(blob, "spss-killer-report.docx");
}
