{
  "hash": "0f06fbbc567894d8f7bfcbfe1ef9e57d",
  "result": {
    "markdown": "---\ntitle: \"Išmokti statistiką per 3 valandas\"\nsubtitle: \"Imčių lyginimas tarp 2 ir daugiau grupių\"\nauthor: \"Paulius Alaburda\"\nformat: \n  revealjs:\n    width: 1600\n---\n\n\n## Ko išmoksime?\n\n-   Pasirinkti tinkamą statistinį testą\n-   Atlikti koreliaciją\n-   Palyginti 2 grupes tarpusavyje\n-   Palyginti 3+ grupes tarpusavyje\n-   Atlikti post-hoc testus\n\n## Ko neišmoksime?\n\n-   Programuoti su R\n-   Tiesinė bei logistinė regresija\n-   Dirbti su matavimais, kurie tarpusavyje yra priklausomi\n\n## Apie jus darau prielaidas\n\n-   Grubiai žinote, kas yra vidurkis, standartinis nuokrypis, variacija\n\n-   Esate bent kartą atlikę statistinį testą (su Excel, SPSS, GraphPad ir pan.)\n\n-   Žinote, kas yra histograma bei stačiakampė diagrama (ang. boxplot)\n\n## Kokių priemonių reikės?\n\nDalyvauti mokymuose galima šiais būdais:\n\n-   Susikurti paskyrą [Posit Cloud](https://posit.cloud/) svetainėje - nereikia siųstis programinės įrangos!\n\n-   Parsisiųsti [RStudio](https://posit.co/download/rstudio-desktop/), jeigu norite naudotis R bei sekti [šį diegimo gidą](../kaip-pasirengti-rstudio/kaip-pasirengti-rstudio.qmd);\n\n-   Parsisiųsti [penguins](../penguins.xlsx) duomenų rinkinį.\n\nTaip pat dalį veiksmų galima atkartoti šiais būdais:\n\n-   Parsiųsti [XLMiner Analysis ToolPak](https://appsource.microsoft.com/en-us/product/office/wa104379190?tab=overview&exp=ubp8), jeigu norite naudotis Excel;\n-   [Handbook of Biological Statistics](http://www.biostathandbook.com/index.html) \"How to do the test\" skiltys (Excel, Web, R, SAS)\n\n## Penguins duomenų rinkinys\n\nPalmer stotyje surinkti matavimai apie pingvinus, duomenys taip pat prieinami `palmerpenguins` bibliotekoje.\n\n![](images/image-1573886618.png)\n\n## Kaip pasirengti Posit Cloud paskyrą?\n\n1.  Užsiregistruoti [čia](https://login.posit.cloud/register).\n2.  Posit pradiniame lange pasirinkti Posit Cloud:\n\n![](images/image-1832016710.png){width=\"338\"}\n\n## Susikurti naują RStudio aplinką\n\n![](images/image-1067007752.png)\n\nPosit jums sukurs virtualią RStudio aplinką. Ši aplinka yra praktiškai tokia pati kaip parsisiuntus RStudio.\n\n# Kas yra tiesiniai modeliai?\n\n## Tiesiniai modeliai ranka\n\n::: columns\n::: {.column width=\"50%\"}\n![Spektrofotometras](images/image-1204024637.png)\n:::\n\n::: {.column width=\"50%\"}\n![Kalibracinė tiesė](images/image-1285293873.png)\n:::\n:::\n\n## Statistika universitete\n\n![](images/image-871015911.png){fig-align=\"center\" width=\"604\"}\n\n## Parametriniai statistiniai testai\n\nDauguma parametrinių statistinių testų yra specifinės tiesinių modelių [versijos](https://lindeloev.github.io/tests-as-linear/).\n\nTiesiniai modeliai turi formą $y = a*x + b$, kur **y** yra mūsų priklausomas kintamasis, o **x** - nepriklausomas kintamasis.\n\n. . .\n\n::: columns\n::: {.column width=\"40%\"}\nPavyzdžiui:\n\n\n::: {.cell}\n::: {.cell-output-display}\n|Baterija | Minutės|\n|:--------|-------:|\n|10%      |       0|\n|20%      |      10|\n|30%      |      20|\n|70%      |      60|\n|100%     |      90|\n:::\n:::\n\n:::\n\n::: {.column width=\"60%\"}\nRemiantis lentele, tiesinis modelis galėtų atrodyti taip:\n\ny = 1\\*x + 10\n:::\n:::\n\n## Bet realybė nėra tokia tvarkinga...\n\nPavyzdžiui, grafike matome `penguins` duomenų rinkinio kūno masės ir pelekų ilgį. Panašu, jog priklausomybė yra tiesiška ir proporcinga -- kokia pora **a** ir **b** kintamųjų geriausiai apibūdintų ryšį?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](statistika_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\n## Kuri tiesė teisinga? Ar tai turėtų būti tiesė apskritai?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](statistika_files/figure-revealjs/unnamed-chunk-3-1.png){fig-pos='c' width=960}\n:::\n:::\n\n\n## OLS -- ordinary least squares (liet. mažiausių kvadratų modelis)\n\n::: columns\n::: {.column width=\"40%\"}\nOLS yra tiesinis metodas, kuris nustato nežinomus parametrus tiesinės regresijos modelyje. Metodo tikslas yra sumažinti skirtumų tarp matavimų ir tiesės kvadratų sumą.\n\n**Kitaip tariant, metodas nustato, kuri tiesė turi mažiausią paklaidą santykiu su mūsų matavimais.**\n:::\n\n::: {.column width=\"60%\"}\n![](images/pca.gif){width=\"460\"}\n:::\n:::\n\n## OLS yra labai patogus modelis\n\n-   **Lengva apibendrinti** - nepaisant nepriklausomo kintamojo, ryšys tarp jo ir priklausomo kintamojo visada išlieka toks pats. Galime drąsiai teigti, jog \"kiekvienas papildomas pingvino gramas yra susijęs su 0.01528 mm ilgesniu peleku\".\n\n. . .\n\n-   **Lengva interpretuoti** - duomenys liko tuose pačiuose matavimo vienetuose. Logistinės regresijos modeliai bei bendriniai tiesiniai modeliai turi būti interpretuojami per šansų santykius bei procentinius pokyčius.\n\n. . .\n\n-   **Greitas** - sudėtingi Bajeso modeliai yra tinkamesni, bet gali trukti minutes (o dideli ir valandas!), kol bus apskaičiuoti.\n\n## OLS turi savo kainą\n\n::: columns\n::: {.column width=\"40%\"}\n-   Tiesiniai modeliai taip pat apskaičiuoja paklaidą - ji turi būti vienoda visoje matavimo aibėje (heteroskedatiškumas)\n-   Tiesiniai modelių paklaida taip pat turi būti pasiskirsčiusi pagal normalųjį skirstinį\n-   Matavimai turi būti nepriklausomi vienas nuo kito\n:::\n\n::: {.column width=\"60%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](statistika_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n:::\n:::\n\n## Kada netaikyti tiesinių modelių?\n\n::: columns\n::: {.column width=\"50%\"}\n-   Ar tiesė yra pakankamai geras būdas apibūdinti mano duomenis?\n\n-   Ar mano imtis yra iš populiacijos, kuri savaime pasiskirsčiusi pagal normalųjį skirstinį?\n\n    -   Likert (pavyzdžiui, 0-5) skalės\n\n    -   Ląstelių skaičius matymo lauke\n\n    -   Ląstelių kolonijos liuminescencija (0-100%)\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](statistika_files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n:::\n:::\n\n# Alternatyva tiesiniams modeliams\n\n## Neparametriniai testai yra tiesiog ranginiai modeliai\n\n::: columns\n::: {.column width=\"70%\"}\nGrubiai, kiekvienas atitinkamas neparametrinis testas pirma ranguoja duomenis, o tada atlieka statistinį testą.\n\n\n::: {.cell}\n::: {.cell-output-display}\n|Baterija | Minutės| Rangas|\n|:--------|-------:|------:|\n|10%      |       0|      1|\n|20%      |      10|      2|\n|30%      |      20|      3|\n|70%      |      60|      4|\n|100%     |      90|      5|\n:::\n:::\n\n:::\n\n::: {.column width=\"30%\"}\nPavyzdžiui, Spearman koreliacijos koeficientas yra identiškas tiesinės regresijos *a* koeficientui, jeigu suvienodiname priklausomo ir nepriklausomo kintamojo standartinius nuokrypius.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n      rho \n0.8399741 \n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n      (Intercept) rank(body_mass_g) \n       27.1732601         0.8424739 \n```\n:::\n:::\n\n:::\n:::\n\n# Susipažinimas su RStudio Cloud\n\nDarbui su RStudio Cloud mums reikės šių paketų:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(c(\"reaxl\",\"ggplot2\",\"dplyr\",\"tidyr\",\"patchwork\",\"car\",\"FSA\"))\n```\n:::\n\n\n## RStudio aplinka\n\n![](images/image-1937977146.png)\n\n# Pagrindiniai statistiniai testai\n\n## Pearson koreliacijos koeficientas\n\n::: columns\n::: {.column width=\"70%\"}\n### Kaip atlikti testą?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(penguins$flipper_length_mm, penguins$body_mass_g, method = \"pearson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  penguins$flipper_length_mm and penguins$body_mass_g\nt = 32.722, df = 340, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.843041 0.894599\nsample estimates:\n      cor \n0.8712018 \n```\n:::\n:::\n\n\nPearson koreliacijos koeficientas yra koeficientas a, jeigu y ir x turi vienodus standartinius nuokrypius. **\"Pearson koreliacijos testas atskleidė, jog koreliacija tarp pelekų ilgio ir kūno masės buvo stipri (r = 0,87, 95% PI \\[0,84-0,89\\] t(340)=32,72, p \\< 0,001).\"**\n:::\n\n::: {.column width=\"30%\"}\n### Kaip pateikti testą?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(data = penguins, aes(x = body_mass_g, y = flipper_length_mm)) + geom_point() + geom_smooth(method = \"lm\")\n```\n\n::: {.cell-output-display}\n![](statistika_files/figure-revealjs/unnamed-chunk-10-1.png){width=960}\n:::\n:::\n\n:::\n:::\n\n## \n\n## Kada koreliacija \"stipri\"?\n\n![Iliustracija iš Danielle Navarro knygos \"Learning Statistics with R\". Kuo koreliacija yra arčiau nulio, tau labiau mūsų duomenys panašūs į debesėlį. 1 ir -1 yra, atitinkamai, tobula teigiama bei neigiama koreliacija.](../posts/kaip-apskaiciuoti-koreliacija/images/image-1260747057.png){alt=\"Iliustracija iš Danielle Navarro knygos \\\"Learning Statistics with R\\\". Kuo koreliacija yra arčiau nulio, tau labiau mūsų duomenys panašūs į debesėlį. 1 ir -1 yra, atitinkamai, tobula teigiama bei neigiama koreliacija.\" fig-align=\"center\" width=\"337\"}\n\n## Spearman koreliacijos koeficienta\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(penguins$flipper_length_mm, penguins$body_mass_g, method = \"spearman\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tSpearman's rank correlation rho\n\ndata:  penguins$flipper_length_mm and penguins$body_mass_g\nS = 1066875, p-value < 2.2e-16\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n      rho \n0.8399741 \n```\n:::\n:::\n\n\nSpearman rho galima interpretuoti kaip rangų pokytį ant y ašies su kiekvienu x rango pokyčiu. **\"Atlikus Spearman ranginį koreliacijos testą, koreliacija tarp pelekų ilgio ir kūno masės buvo stipri (r = 0,840, p \\< 0,001).\"**\n\n## Stjudento t-testas (neporinis)\n\n::: columns\n::: {.column width=\"50%\"}\n### Kaip atlikti?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(data = penguins, flipper_length_mm ~ sex)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  flipper_length_mm by sex\nt = -4.8079, df = 325.28, p-value = 2.336e-06\nalternative hypothesis: true difference in means between group female and group male is not equal to 0\n95 percent confidence interval:\n -10.064811  -4.219821\nsample estimates:\nmean in group female   mean in group male \n            197.3636             204.5060 \n```\n:::\n:::\n\n\n\"Atlikus Stjudento t-testą, vidutinis pelekų ilgio skirtumas tarp pingvinų lyčių buvo 7,14 mm, skirtumas buvo statistiškai reikšmingas (t(325,28) = 4,80, 95% PI \\[4,21-10,06\\], p \\< 0,001).\"\n:::\n\n::: {.column width=\"50%\"}\n### Kaip vizualizuoti?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = penguins, aes(x = sex, y = flipper_length_mm)) + geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](statistika_files/figure-revealjs/unnamed-chunk-13-1.png){width=960}\n:::\n:::\n\n:::\n:::\n\n## Stjudento t-testas - diagnostika\n\n-   Stjudento t-testui duomenys turi būti pasiskirstę pagal normalųjį skirstinį\n\n-   Matavimai turi būti nepriklausomi vienas nuo kito\n\n-   Naudodami Welch t-testą galime ignoruoti skirtingų variacijų prielaidą\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = penguins, aes(x = flipper_length_mm)) + geom_histogram() + facet_grid(~sex)\n```\n\n::: {.cell-output-display}\n![](statistika_files/figure-revealjs/unnamed-chunk-14-1.png){width=960}\n:::\n:::\n\n\n## Mann-Whitney U\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(data = penguins, flipper_length_mm ~ sex)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  flipper_length_mm by sex\nW = 9547, p-value = 9.011e-07\nalternative hypothesis: true location shift is not equal to 0\n```\n:::\n:::\n\n\n\"Atlikus Mann-Whitney U testą, pelekų ilgio skirtumas tarp lyčių buvo statistiškai reikšmingas (W = 9547, p \\< 0,001).\"\n\n## Poruotas Stjudento t-testas\n\n::: columns\n::: {.column width=\"50%\"}\n### Kaip atlikti?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(penguins$bill_length_mm, penguins$bill_depth_mm, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPaired t-test\n\ndata:  penguins$bill_length_mm and penguins$bill_depth_mm\nt = 79.505, df = 341, p-value < 2.2e-16\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n 26.10846 27.43306\nsample estimates:\nmean difference \n       26.77076 \n```\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n### Kaip pasitikrinti?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = penguins, aes(x = bill_length_mm-bill_depth_mm)) + geom_histogram()\n```\n\n::: {.cell-output-display}\n![](statistika_files/figure-revealjs/unnamed-chunk-17-1.png){width=960}\n:::\n:::\n\n:::\n:::\n\n## Wilcoxon ranginis testas\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(penguins$bill_length_mm, penguins$bill_depth_mm, paired = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWilcoxon signed rank test with continuity correction\n\ndata:  penguins$bill_length_mm and penguins$bill_depth_mm\nV = 58653, p-value < 2.2e-16\nalternative hypothesis: true location shift is not equal to 0\n```\n:::\n:::\n\n\n## VIenpusė ANOVA\n\n::: columns\n::: {.column width=\"60%\"}\n### Kaip atlikti?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy.anova <- aov(data = penguins, body_mass_g ~ species)\n\nsummary(my.anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             Df    Sum Sq  Mean Sq F value Pr(>F)    \nspecies       2 146864214 73432107   343.6 <2e-16 ***\nResiduals   339  72443483   213698                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n2 observations deleted due to missingness\n```\n:::\n:::\n\n\nAdelie rūšies pingvinai vidutiniškai svėrė 3,70 kg (SD = 0,46), Chinstrap svėrė 3,73 kg (SD = 0,38), Gentoo svėrė 5,08 kg (SD = 0,5). Skirtumas tarp rūšių vidurkių buvo statistiškai reikšmingas (F(2,339) = 343,6, p \\< 0,001).\n:::\n\n::: {.column width=\"40%\"}\n### Kaip vizualizuoti?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins, aes(x = species, y = body_mass_g)) + geom_boxplot() + labs(x = \"Rūšis\", y = \"Kūno masė, g\")\n```\n\n::: {.cell-output-display}\n![](statistika_files/figure-revealjs/unnamed-chunk-20-1.png){width=960}\n:::\n:::\n\n:::\n:::\n\n## Kas yra residuals?\n\nResiduals yra skirtumai tarp tiesinio modelio prognozuojamos reikšmės ir realios reikšmės.\n\n::: columns\n::: {.column width=\"40%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n| body_mass_g| predicted|  residuals|\n|-----------:|---------:|----------:|\n|        3750|  3700.662|   49.33775|\n|        3800|  3700.662|   99.33775|\n|        3250|  3700.662| -450.66225|\n|        3450|  3700.662| -250.66225|\n|        3650|  3700.662|  -50.66225|\n|        3625|  3700.662|  -75.66225|\n:::\n:::\n\n:::\n\n::: {.column width=\"40%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n![](statistika_files/figure-revealjs/unnamed-chunk-22-1.png){width=960}\n:::\n:::\n\n:::\n:::\n\n## ANOVA diagnostika - heteroskedatiškumas\n\nANOVA homoskedatiškumo prielaidą tikriname taip:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\n\nleveneTest(my.anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLevene's Test for Homogeneity of Variance (center = median)\n       Df F value   Pr(>F)   \ngroup   2  5.1203 0.006445 **\n      339                    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nLevene testas rodo, jog mes sulaužėme homogeniškos variacijos (homoskedatiškumo) prielaidą ir tokiu būdu mūsų paklaidos nebėra [tikslios](https://stats.stackexchange.com/questions/22800/what-are-the-dangers-of-violating-the-homoscedasticity-assumption-for-linear-reg).\n\n## ANOVA diagnostika - residuals su Shapiro-Wilk testu\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(residuals(my.anova))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tShapiro-Wilk normality test\n\ndata:  residuals(my.anova)\nW = 0.99166, p-value = 0.05118\n```\n:::\n:::\n\n\n## ANOVA diagnostika - residuals grafiškai\n\n::: columns\n::: {.column width=\"60%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(patchwork)\n\np1 <- ggplot() + aes(sample = residuals(my.anova)) + stat_qq() + stat_qq_line(color = \"red\")\n\np2 <- ggplot() + aes(x = residuals(my.anova)) + geom_density()\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](statistika_files/figure-revealjs/unnamed-chunk-25-1.png){width=960}\n:::\n:::\n\n:::\n\n::: {.column width=\"40%\"}\nQQ grafikas didžiąja dalimi atitinka tiesę, bet nukrypsta ties labai mažomis ir labai didelėmis reikšmėmis. Histograma taip pat rodo, jog \"uodegos\" turi daugiau reikšmių negu idealiai norėtume.\n:::\n:::\n\n## Post-hoc testai - Tukey HSD\n\nTukey HSD (Honestly Significant Difference) yra standartinis būdas patikrinti porinius skirtumus tarp grupių.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(my.anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = body_mass_g ~ species, data = penguins)\n\n$species\n                       diff       lwr       upr     p adj\nChinstrap-Adelie   32.42598 -126.5002  191.3522 0.8806666\nGentoo-Adelie    1375.35401 1243.1786 1507.5294 0.0000000\nGentoo-Chinstrap 1342.92802 1178.4810 1507.3750 0.0000000\n```\n:::\n:::\n\n\n## Kruskal-Wallis testas\n\n::: columns\n::: {.column width=\"40%\"}\n### Kaip atlikti?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkruskal.test(data = penguins, body_mass_g ~ species)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  body_mass_g by species\nKruskal-Wallis chi-squared = 217.6, df = 2, p-value < 2.2e-16\n```\n:::\n:::\n\n\nAdelie rūšies pingvinai vidutiniškai svėrė 3,70 kg (SD = 0,46), Chinstrap svėrė 3,73 kg (SD = 0,38), Gentoo svėrė 5,08 kg (SD = 0,5). Skirtumas tarp rūšių buvo statistiškai reikšmingas (χ^2^(2) = 217,6, p \\< 0,001).\n:::\n\n::: {.column width=\"60%\"}\n### Kaip vizualizuoti?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins, aes(x = species, y = body_mass_g)) + geom_boxplot() + geom_jitter(alpha = 0.3) + labs(x = \"Rūšis\", y = \"Kūno masė, g\")\n```\n\n::: {.cell-output-display}\n![](statistika_files/figure-revealjs/unnamed-chunk-28-1.png){width=960}\n:::\n:::\n\n:::\n:::\n\n## Post-hoc Dunn testas\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(FSA)\n\ndunnTest(body_mass_g ~ species, data=penguins, method=\"bh\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          Comparison           Z      P.unadj        P.adj\n1 Adelie - Chinstrap  -0.3973552 6.911056e-01 6.911056e-01\n2    Adelie - Gentoo -13.8280088 1.727360e-43 5.182080e-43\n3 Chinstrap - Gentoo -10.7303390 7.332668e-27 1.099900e-26\n```\n:::\n:::\n\n\n## Dvipusė ANOVA\n\n::: columns\n::: {.column width=\"40%\"}\n### Kaip atlikti\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy.anova.2 <- aov(data = penguins, body_mass_g ~ species + sex + species:sex)\n\nsummary(my.anova.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             Df    Sum Sq  Mean Sq F value   Pr(>F)    \nspecies       2 145190219 72595110 758.358  < 2e-16 ***\nsex           1  37090262 37090262 387.460  < 2e-16 ***\nspecies:sex   2   1676557   838278   8.757 0.000197 ***\nResiduals   327  31302628    95727                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n11 observations deleted due to missingness\n```\n:::\n:::\n\n:::\n\n::: {.column width=\"60%\"}\n### Kaip vizualizuoti\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins, aes(x = species, y = body_mass_g, fill = sex)) + geom_boxplot() + labs(x = \"Rūšis\", y = \"Kūno masė, g\", fill = \"Lytis\")\n```\n\n::: {.cell-output-display}\n![](statistika_files/figure-revealjs/unnamed-chunk-31-1.png){width=960}\n:::\n:::\n\n:::\n:::\n\n## Dvipusės ANOVA interpretacija\n\n::: columns\n::: {.column width=\"60%\"}\n### Kintamųjų įtaka\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lsr)\n\netaSquared(my.anova.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 eta.sq eta.sq.part\nspecies     0.666179534  0.82082499\nsex         0.172304745  0.54231166\nspecies:sex 0.007788532  0.05083682\n```\n:::\n:::\n\n\nANOVA modelis paaiškina 84,63% pingvinų svorio variacijos. Pingvinų rūšis buvo pagrindinis veiksnys lemiantis pingvinų svorį ir paaiškino 66,62% variacijos. Lytis turėjo mažesnę įtaką variacijai ir paaiškino tik 17,23% variacijos. Sąveika tarp rūšies ir lyties turėjo itin mažą įtaką (0,77%).\n:::\n\n::: {.column width=\"40%\"}\n### Vidutinis svoris grupėje\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(effects)\n\neff <- effect( term = \"species*sex\", mod = my.anova.2 )\nsummary(eff)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n species*sex effect\n           sex\nspecies       female     male\n  Adelie    3368.836 4043.493\n  Chinstrap 3527.206 3938.971\n  Gentoo    4679.741 5484.836\n\n Lower 95 Percent Confidence Limits\n           sex\nspecies       female     male\n  Adelie    3297.597 3972.255\n  Chinstrap 3422.821 3834.586\n  Gentoo    4599.820 5406.905\n\n Upper 95 Percent Confidence Limits\n           sex\nspecies       female     male\n  Adelie    3440.074 4114.731\n  Chinstrap 3631.590 4043.355\n  Gentoo    4759.662 5562.767\n```\n:::\n:::\n\n:::\n:::\n\n## Dvipusės ANOVA Tukey's HSD\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(my.anova.2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = body_mass_g ~ species + sex + species:sex, data = penguins)\n\n$species\n                       diff       lwr       upr     p adj\nChinstrap-Adelie   26.92385  -80.0258  133.8735 0.8241288\nGentoo-Adelie    1386.27259 1296.3070 1476.2382 0.0000000\nGentoo-Chinstrap 1359.34874 1248.6108 1470.0866 0.0000000\n\n$sex\n                diff      lwr      upr p adj\nmale-female 667.4577 600.7462 734.1692     0\n\n$`species:sex`\n                                     diff       lwr       upr     p adj\nChinstrap:female-Adelie:female   158.3703  -25.7874  342.5279 0.1376213\nGentoo:female-Adelie:female     1310.9058 1154.8934 1466.9181 0.0000000\nAdelie:male-Adelie:female        674.6575  527.8486  821.4664 0.0000000\nChinstrap:male-Adelie:female     570.1350  385.9773  754.2926 0.0000000\nGentoo:male-Adelie:female       2116.0004 1962.1408 2269.8601 0.0000000\nGentoo:female-Chinstrap:female  1152.5355  960.9603 1344.1107 0.0000000\nAdelie:male-Chinstrap:female     516.2873  332.1296  700.4449 0.0000000\nChinstrap:male-Chinstrap:female  411.7647  196.6479  626.8815 0.0000012\nGentoo:male-Chinstrap:female    1957.6302 1767.8040 2147.4564 0.0000000\nAdelie:male-Gentoo:female       -636.2482 -792.2606 -480.2359 0.0000000\nChinstrap:male-Gentoo:female    -740.7708 -932.3460 -549.1956 0.0000000\nGentoo:male-Gentoo:female        805.0947  642.4300  967.7594 0.0000000\nChinstrap:male-Adelie:male      -104.5226 -288.6802   79.6351 0.5812048\nGentoo:male-Adelie:male         1441.3429 1287.4832 1595.2026 0.0000000\nGentoo:male-Chinstrap:male      1545.8655 1356.0392 1735.6917 0.0000000\n```\n:::\n:::\n\n\n## O gal tiesiog tiesinis modelis?\n\n::: columns\n::: {.column width=\"60%\"}\n### Kaip atlikti?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy.lm.3 <- lm(data = penguins, body_mass_g ~ species*sex)\n\nsummary(my.lm.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = body_mass_g ~ species * sex, data = penguins)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-827.21 -213.97   11.03  206.51  861.03 \n\nCoefficients:\n                         Estimate Std. Error t value Pr(>|t|)    \n(Intercept)               3368.84      36.21  93.030  < 2e-16 ***\nspeciesChinstrap           158.37      64.24   2.465  0.01420 *  \nspeciesGentoo             1310.91      54.42  24.088  < 2e-16 ***\nsexmale                    674.66      51.21  13.174  < 2e-16 ***\nspeciesChinstrap:sexmale  -262.89      90.85  -2.894  0.00406 ** \nspeciesGentoo:sexmale      130.44      76.44   1.706  0.08886 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 309.4 on 327 degrees of freedom\n  (11 observations deleted due to missingness)\nMultiple R-squared:  0.8546,\tAdjusted R-squared:  0.8524 \nF-statistic: 384.3 on 5 and 327 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n\"Tiesinės regresijos modelis, kur rūšis ir lytis buvo nepriklausomi kintamieji, paaiškina 85,24% kūno svorio variacijos (p \\< 0,001). Vidutinis Adelie rūšies patelė vidutiniškai svėrė 3,4 kg. Chinstrap rūšies pingvinai svėrė 158 gramais daugiau, skirtumas buvo statistiškai reikšmingas (SE = 64,24, t = 2,47, p = 0,01). Gentoo rūšies pingvinai buvo 1,3 kg sunkesni (SE = 54,42, t = 24,09, p \\< 0,001). Vidutiniškai patinai tarp visų rūšių buvo sunkesni 674 gramais negu patelės (SE = 51,21, t = 13,17, p \\< 0,001).\"\n:::\n\n::: {.column width=\"40%\"}\n### Kaip vizualizuoti?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(penguins, aes(x = species, y = body_mass_g, fill = sex)) + geom_boxplot() + labs(x = \"Rūšis\", y = \"Kūno masė, g\")\n```\n\n::: {.cell-output-display}\n![](statistika_files/figure-revealjs/unnamed-chunk-36-1.png){width=960}\n:::\n:::\n\n:::\n:::\n\n## Diagnostiniai įrankiai taip pat veikia!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleveneTest(my.lm.3)\n\nshapiro.test(residuals(my.lm.3))\n\np1 <- ggplot() + aes(sample = residuals(my.lm.3)) + stat_qq() + stat_qq_line(color = \"red\")\n\np2 <- ggplot() + aes(x = residuals(my.lm.3)) + geom_density()\n\np1 + p2\n```\n:::\n\n\n# Apibendrinimas\n\n## Ką reikia žinoti?\n\n-   Naudokitės grafikais prieš atlikdami bet kokį statistinį testą\n\n-   Statistinio testo pasirinkimą lemia ne tik surinkti duomenys, bet ir tyrimo dizainas bei mūsų žinios apie tyrimo temą\n",
    "supporting": [
      "statistika_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\r\n<script>\r\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\r\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\r\n  // slide changes (different for each slide format).\r\n  (function () {\r\n    // dispatch for htmlwidgets\r\n    function fireSlideEnter() {\r\n      const event = window.document.createEvent(\"Event\");\r\n      event.initEvent(\"slideenter\", true, true);\r\n      window.document.dispatchEvent(event);\r\n    }\r\n\r\n    function fireSlideChanged(previousSlide, currentSlide) {\r\n      fireSlideEnter();\r\n\r\n      // dispatch for shiny\r\n      if (window.jQuery) {\r\n        if (previousSlide) {\r\n          window.jQuery(previousSlide).trigger(\"hidden\");\r\n        }\r\n        if (currentSlide) {\r\n          window.jQuery(currentSlide).trigger(\"shown\");\r\n        }\r\n      }\r\n    }\r\n\r\n    // hookup for slidy\r\n    if (window.w3c_slidy) {\r\n      window.w3c_slidy.add_observer(function (slide_num) {\r\n        // slide_num starts at position 1\r\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\r\n      });\r\n    }\r\n\r\n  })();\r\n</script>\r\n\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}