{
  "hash": "97ae17e6666af9f0b7cda6943c9707a1",
  "result": {
    "markdown": "---\ntitle: \"Kaip atlikti koreliaciją?\"\neditor: visual\nreference-location: document\nwarning: false\ntitle-block-banner: red\n---\n\n\nKoreliacijos yra aprašomosios statistikos būdas apibūdinti santykį tarp dviejų kintamųjų. Koreliacijos yra 3 rūšių: Pearson, Spearman ir Kendall. Kendall ir Spearman tarpusavyje metodiškai veikia taip pat, todėl padengsime tik Pearson ir Spearman koreliacijas.\n\n# Pearson koreliacijos koeficientas\n\nPearson'o koreliacijos koeficientą labai nesudėtinga paaiškinti: įsivaizduokime tiesę, kurią nubrėžtume su funkcija y = f(x):\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](kaip-apskaiciuoti-koreliacija_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\nNelendant į matematines detales, kuo arčiau mūsų matavimai yra arčiau šios linijos, tuo koreliacijos koeficientas bus didesnis. Priešingai, jeigu taškai yra arčiau linijos, kuomet y reikšmės mažėja didėjant x reikšmėms, tuo koreliacijos koeficientas bus mažesnis. Koreliacijos koeficientas 1,0 ir -1,0 yra šios linijos.\n\nPajutimui, taip atrodo duomenys su skirtingais koreliacijos koeficientais[^1]:\n\n[^1]: Taip pat labai rekomenduoju šitą žaidimą išbandyti intuiciją apie koreliacijas: https://www.guessthecorrelation.com/\n\n![Iliustracija iš Danielle Navarro knygos \"Learning Statistics with R\". Kuo koreliacija yra arčiau nulio, tau labiau mūsų duomenys panašūs į debesėlį. 1 ir -1 yra, atitinkamai, tobula teigiama bei neigiama koreliacija.](images/image-1260747057.png)\n\nApskaičiuoti koreliacijos koeficientą galima ir su R, ir su Excel:\n\n::: panel-tabset\n## R\n\nR `cor()` funkcija leidžia lyginti kelis stulpelis iškart, o cor.test() taip pat pateikia statistinio testo rezultatus.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(iris$Sepal.Length, iris$Sepal.Width)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  iris$Sepal.Length and iris$Sepal.Width\nt = -1.4403, df = 148, p-value = 0.1519\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.27269325  0.04351158\nsample estimates:\n       cor \n-0.1175698 \n```\n:::\n:::\n\n\nKoreliacijos koeficientas yra -0.118. Statistinio testo rezultatai šiuo atveju nėra visiškai sąžiningi, nes tai yra tiesinės regresijos rezultatai. Juos laisvai galima raportuoti, bet tai parodo, jog tikriausiai norime tiesiog atlikti tiesinę regresiją.\n\n## Excel\n\nExcel grąžina tik patį koreliacijos koeficientą, bet su XLMiner Toolpak galima lyginti kelis stulpelius vienu metu! Šiuo atveju lygindami stulpelius gavome stiprų teigiamą koreliacijos koeficientą 0,926.\n\n![](images/Recording%202023-04-20%20232338.gif)\n:::\n\n# Spearman koreliacijos koeficientas\n\nPearson'o koreliacijos pagrindinis trūkumas - jis tinkamas tiesiniams ryšiams. Kitaip tariant, koreliacijos koeficientas nusako, kaip gerai mūsų dviejų kintamųjų matavimai nugula aplinkui tobulą tiesę (r = 1.0). Nemažai koreliacijų mūsų aplinkoje nėra tiesiškos, pavyzdžiui, truputis pastangų rengiantis egzaminui turės didelę įtaką pažymiui (tarkim, nuo 4 iki 7), bet papildomos pastangos padidins pažymį tik truputį (nuo 7 iki 8), Pearson'o koreliacijos koeficientas nepateiks teisingo įverčio. Tokiu atveju turime naudoti Spearman'o koreliaciją.\n\nSpearman koreliacija yra labai analogiška Wilcoxon dviejų imčių testui arba Kruskal-Wallis testui. Pirma, mūsų duomenų rinkinys yra paverčiamas į rangines reikšmes, o tada - skaičiuojamas gautų rangų koreliacijos koeficientas. Excel negali apskaičiuoti rangų koreliacijos, todėl turime pasikliauti R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(iris$Sepal.Length, iris$Sepal.Width, method = \"spearman\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tSpearman's rank correlation rho\n\ndata:  iris$Sepal.Length and iris$Sepal.Width\nS = 656283, p-value = 0.04137\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n       rho \n-0.1667777 \n```\n:::\n:::\n\n\n# Kaip raportuoti koreliaciją?\n\nLiteratūroje galima rasti, jog koreliacijas galima grubiai skirstyti į silpnas, vidutines ir stiprias. Toks skirstymas priklauso nuo tyrimų krypties. Pavyzdžiui, sociologijoje bei psichologijoje 0,4 koreliacija jau būtų gana įspūdinga, nors dažnai literatūroje tai bus laikome vidutiniškai stipria koreliacija. Nepaisant konteksto, bendras skirstymas atrodo taip:\n\n-   0-0,19 - labai silpna koreliacija\n\n-   0,2-0,39 - silpna koreliacija\n\n-   0,4-0,59 - vidutinė koreliacija\n\n-   0,6-0,79 - stipri koreliacija\n\n-   0,8-1 - labai stipri koreliacija\n\nPavyzdžiui, aukščiau esantį Spearman testą galėtume apibūdinti taip:\n\n::: {.callout-note icon=\"false\"}\nRanginė koreliacija tarp taurėlapių pločio ir taurėlapių ilgio buvo neigiama ir labai silpna (r = -0,167, S = 656283, p = 0.04).\n:::\n\nGrafiškai koreliacijas labai rekomenduoju pateikti, nes tai yra geriausias būdas įvertinti, ar teisingai buvo pasirinktas Spearman arba Pearson koreliacijos testas:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(iris, aes(x = Sepal.Length, y = Sepal.Width)) + geom_point() + geom_smooth(method = \"lm\") + labs(title = \"Koreliacija tarp taurėlapių pločio ir ilgio\", subtitle = \"Kuri yra neteisinga - pašnekėkime apie Simpsono paradoksą\")\n```\n\n::: {.cell-output-display}\n![](kaip-apskaiciuoti-koreliacija_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n# Simpsono paradoksas\n\nKoreliacijoms grafinis atvaizdavimas yra kritiškai svarbus. Aukščiau buvęs grafikas rodo taurėlapio pločio ir ilgio santykį. Įprastai taurėlapiai turi standartinę formą, kuri smarkiai nekinta priklausomai nuo dydžio. Dėl to tikėtumėmės, jog koreliacija bus stipri. Antra, grafike aukščiau galima įžvelgti subgrupes. Jeigu pridėti rūšies parametrą nuspalvinti savo taškus, tai ir pamatytume:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, color = Species)) + geom_point() + geom_smooth(method = \"lm\") + labs(title = \"Koreliacija tarp taurėlapių pločio ir ilgio\", subtitle = \"Atsižvelgdami į rūšį gauname teisingą tendenciją\")\n```\n\n::: {.cell-output-display}\n![](kaip-apskaiciuoti-koreliacija_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nApskaičiuoti subgrupių koeficientus galime keliais būdais: arba su R naudoti `group_by()` funkciją, arba atlikti 3 koreliacijas filtruojant duomenis ranka. Taip atrodo kodas, jeigu norime apskaičiuoti koreliaciją subgrupėms:\n\n\n::: {.cell}\n\n```{.r .cell-code}\niris %>% \n  group_by(Species) %>% \n  summarise(stuff = cor(.data$Sepal.Length, .data$Sepal.Width)) %>% \n  knitr::kable()\n```\n\n::: {.cell-output-display}\n|Species    |     stuff|\n|:----------|---------:|\n|setosa     | 0.7425467|\n|versicolor | 0.5259107|\n|virginica  | 0.4572278|\n:::\n:::\n\n\nSmulki korekcija apvertė ženklą ir padarė, jog koreliacija iš silpnos taptų vidutinė!\n",
    "supporting": [
      "kaip-apskaiciuoti-koreliacija_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}