{
  "hash": "a6893634303cc2d8c31cb25f56016fc9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Kaip naudoti Stjudento t-testą?\"\ndescription: \"Palyginti dviejų imčių vidurkius yra standartinė užduotis atliekant tyrimus. Sužinokite, kaip ir kada taikyti Stjudento t-testą.\"\ndate: \"2023-04-22\"\ncategories: [statistika, t-testas, R]\nimage: kada-rinktis-t-testa_files/figure-html/unnamed-chunk-1-1.png\neditor: visual\nexecute:\n  warning: false\n  message: false\ntoc: true\n---\n\n\n\nPalyginti dviejų imčių vidurkius yra standartinė užduotis atliekant tyrimus, todėl Stjudento t-testas yra vienas dažniausių taikomų statistinių testų. Jeigu atliekate tyrimus, tikėtina, jog susidursite su duomenimis, kur t-testas bus tinkamas. Dėl to svarbu suprasti, kada taikyti testą, kaip jį interpretuoti bei kaip jį pateikti publikacijoje.\n\n# Kam skirtas t-testas?\n\nT-testas yra skirtas palyginti dviejų imčių vidurkius. Tai gali būti:\n\n- **Nepriklausomos imtys**: pavyzdžiui, vyrai ir moterys\n- **Priklausomos (porinės) imtys**: pavyzdžiui, matavimai prieš ir po gydymo tam pačiam pacientui\n\n# Kada rinktis t-testą?\n\nT-testą galima atlikti su tolydžiu kintamuoju, kurį galima padalinti į dvi grupes. Tolydų kintamąjį toliau vadinsime priklausomu kintamuoju, o savo grupių kintamąjį - nepriklausomu kintamuoju.\n\nPirma, priklausomas kintamasis turi būti tolydus, t.y. jis turi gebėti įgyti daug skirtingų reikšmių. Tinkami priklausomi kintamieji:\n\n-   **Matavimai, kurie gali įgyti be galo didelį kiekį reikšmių**: ūgis, svoris, amžius ir pan.\n-   **Sudėtiniai skaičiai**, pavyzdžiui, ląstelių skaičius matymo lauke, euzinofilų skaičius kraujyje ir pan.\n-   **Ranginiai klausimai** (iš dalies) - t-testas yra pakankamai atsparus nuokrypiams nuo normalumo.\n\nAntra, priklausomas kintamasis, padalintas į 2 grupes, turi turėti panašią variaciją (t.y. standartinį nuokrypį) ir turi būti pasiskirstęs pagal normalųjį skirstinį. \n\n::: {.callout-tip}\n## Patarimas\nR naudoja Welch t-testą, kuriam nesvarbi skirtinga variacija. Todėl variacijos testavimas dirbant su R nėra būtinas!\n:::\n\n## Normalumo tikrinimas\n\nNormalumą galima patikrinti vizualiai su QQ grafiku:\n\n::: panel-tabset\n## R\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(iris, aes(sample = Sepal.Length)) + \n  stat_qq() + \n  stat_qq_line(color = \"red\") + \n  facet_wrap(~Species) + \n  labs(title = \"3 vilkdalgių rūšių taurėlapių ilgio QQ grafikas\", \n       subtitle = \"iris duomenų rinkinys; kuo arčiau linijos centre yra taškai, tuo geriau.\")\n```\n\n::: {.cell-output-display}\n![](kada-rinktis-t-testa_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n\n## Excel\n\nQQ grafikas Excel'e sukuriamas šiek tiek kitaip - reikia naudoti specialų įrankį arba rankiniu būdu skaičiuoti teorines kvantiles.\n:::\n\n# Kaip atlikti t-testą?\n\n::: panel-tabset\n## R\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(data = iris, Sepal.Length ~ Species, subset = Species %in% c(\"setosa\", \"versicolor\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  Sepal.Length by Species\nt = -10.521, df = 86.538, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group setosa and group versicolor is not equal to 0\n95 percent confidence interval:\n -1.1057074 -0.7542926\nsample estimates:\n    mean in group setosa mean in group versicolor \n                   5.006                    5.936 \n```\n\n\n:::\n:::\n\n\n\n## Excel\n\nExcel'e t-testą galima atlikti naudojant `T.TEST` funkciją arba Data Analysis ToolPak.\n:::\n\n# Kaip interpretuoti t-testą?\n\nT-testo rezultate svarbiausios reikšmės:\n\n1. **t reikšmė** - kuo toliau nuo 0, tuo didesnis skirtumas\n2. **p reikšmė** - jei < 0.05, skirtumas yra statistiškai reikšmingas\n3. **Pasikliautinasis intervalas** - parodo skirtumų intervalą\n\n# Kaip raportuoti t-testą?\n\nŠtai šablonas, kurį galite naudoti:\n\n> \"Atlikus nepriklausomų imčių t-testą, nustatyta, kad setosa rūšies taurėlapių ilgis buvo statistiškai reikšmingai mažesnis (M = 5.01, SD = 0.35) nei versicolor rūšies (M = 5.94, SD = 0.52); t(86.54) = -10.52, p < 0.001.\"\n\n# Jeigu negaliu taikyti t-testo?\n\nJeigu Stjudento t-testas nėra tinkamas, tokiu atveju reikėtų taikyti Mann-Whitney U testą. Aprašą apie testą galima rasti [čia](../kada-rinktis-mann-whitney/kada-rinktis-mann-whitney.qmd).\n",
    "supporting": [
      "kada-rinktis-t-testa_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}